// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8jEMcf9kGFKXGWCIT0VdgA_0-x20sV0',
    appId: '1:688999576762:web:9a86aaa79f2b5a69e73e83',
    messagingSenderId: '688999576762',
    projectId: 'tronicaassociates-8b74b',
    authDomain: 'tronicaassociates-8b74b.firebaseapp.com',
    storageBucket: 'tronicaassociates-8b74b.appspot.com',
    measurementId: 'G-QK2SFM6KT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsiTTkpUJ8nUcpH89-xqiHCge9hqEl52U',
    appId: '1:688999576762:android:4a3812a1840b37f9e73e83',
    messagingSenderId: '688999576762',
    projectId: 'tronicaassociates-8b74b',
    storageBucket: 'tronicaassociates-8b74b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDVbuLLMPaGwN_ldhshPHtL5lzOH1ls_Y',
    appId: '1:688999576762:ios:bac2983b22b10a44e73e83',
    messagingSenderId: '688999576762',
    projectId: 'tronicaassociates-8b74b',
    storageBucket: 'tronicaassociates-8b74b.appspot.com',
    iosClientId: '688999576762-sdstmsmqc78b9k6unr49m15tja1b0oo4.apps.googleusercontent.com',
    iosBundleId: 'com.innovativescripts.tronicassociates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDVbuLLMPaGwN_ldhshPHtL5lzOH1ls_Y',
    appId: '1:688999576762:ios:bac2983b22b10a44e73e83',
    messagingSenderId: '688999576762',
    projectId: 'tronicaassociates-8b74b',
    storageBucket: 'tronicaassociates-8b74b.appspot.com',
    iosClientId: '688999576762-sdstmsmqc78b9k6unr49m15tja1b0oo4.apps.googleusercontent.com',
    iosBundleId: 'com.innovativescripts.tronicassociates',
  );
}
